apiVersion: v1
kind: Namespace
metadata:
  name: app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp2
  namespace: app2
  labels:
    app: kubeapp2
spec:
  selector:
    matchLabels:
      app: kubeapp2
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: app2
      labels:
        app: kubeapp2
    spec:
      containers:
        - name: app
          image: kubeapp2
          imagePullPolicy: Never
          ports:
            - containerPort: 8891